# version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: Chi_Icon
    ports:
      - "5000:5000"
    env_file:
      - .env 
#     environment:
#       MYSQL_HOST: mysql
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       MYSQL_DB: ${MYSQL_DATABASE}
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql:5.7
#     restart: always
#     container_name: Chi_Icon_mysql
#     networks:
#       - networkName
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#     ports:
#       - "3307:3307"
#     volumes:
#       - mysql_data:/var/lib/mysql

# networks:
#   networkName:
#     driver: bridge

# volumes:
#   mysql_data:
